"use client";
import { useCallback,useEffect,useRef,useState } from "react";
type Mode="intro"|"playing"|"ended";type Level="calm"|"standard"|"overload";
type Point={x:number;y:number;r:number;vx?:number;vy?:number;life?:number;age?:number;maxLife?:number};
type World={player:Point;signals:Point[];noise:Point[];echoes:Point[];particles:Point[];score:number;combo:number;health:number;started:number;time:number;spawn:number;flash:number;level:Level};
const RUN_SECONDS=120;
const LEVELS:Record<Level,{label:string;note:string;spawn:number;noiseChance:number;chase:number;damage:number;drift:number;decay:number}>={calm:{label:"Calm",note:"More space · slower noise",spawn:1.25,noiseChance:.58,chase:.72,damage:12,drift:.55,decay:.45},standard:{label:"Standard",note:"Balanced transmission",spawn:1,noiseChance:.82,chase:1,damage:16,drift:1,decay:.7},overload:{label:"Overload",note:"Dense field · fast noise",spawn:.72,noiseChance:1,chase:1.42,damage:20,drift:1.65,decay:1}};
const freshWorld=(level:Level):World=>({player:{x:400,y:320,r:32,vx:0,vy:0},signals:[],noise:[],echoes:[],particles:[],score:0,combo:1,health:100,started:0,time:RUN_SECONDS,spawn:0,flash:0,level});

export default function SignalDrift(){
 const canvasRef=useRef<HTMLCanvasElement>(null),frameRef=useRef(0),modeRef=useRef<Mode>("intro"),levelRef=useRef<Level>("standard");
 const inputRef=useRef({x:0,y:0,tx:0,ty:0,pointer:false}),worldRef=useRef<World>(freshWorld("standard"));
 const[mode,setMode]=useState<Mode>("intro"),[level,setLevel]=useState<Level>("standard"),[score,setScore]=useState(0),[health,setHealth]=useState(100),[time,setTime]=useState(RUN_SECONDS),[combo,setCombo]=useState(1);
 const chooseLevel=(next:Level)=>{levelRef.current=next;setLevel(next)};
 const begin=useCallback(()=>{const c=canvasRef.current;if(!c)return;const next=freshWorld(levelRef.current);next.player={x:(c.clientWidth||800)/2,y:(c.clientHeight||650)/2,r:32,vx:0,vy:0};next.started=performance.now();worldRef.current=next;modeRef.current="playing";setMode("playing");setScore(0);setHealth(100);setTime(RUN_SECONDS);setCombo(1)},[]);

 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();if((e.key===" "||e.key==="Enter")&&modeRef.current!=="playing")begin();const i=inputRef.current,k=e.key.toLowerCase();if(k==="arrowleft"||k==="a")i.x=-1;if(k==="arrowright"||k==="d")i.x=1;if(k==="arrowup"||k==="w")i.y=-1;if(k==="arrowdown"||k==="s")i.y=1};const up=(e:KeyboardEvent)=>{const i=inputRef.current,k=e.key.toLowerCase();if(["arrowleft","arrowright","a","d"].includes(k))i.x=0;if(["arrowup","arrowdown","w","s"].includes(k))i.y=0};addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up)}},[begin]);

 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;const resize=()=>{const d=Math.min(devicePixelRatio,2),r=canvas.getBoundingClientRect();canvas.width=Math.floor(r.width*d);canvas.height=Math.floor(r.height*d);ctx.setTransform(d,0,0,d,0,0)};resize();addEventListener("resize",resize);let last=performance.now(),uiTick=0;const rnd=(max:number,min=0)=>min+Math.random()*(max-min);const spawn=(arr:Point[],r:number,life:number)=>{const w=canvas.clientWidth,h=canvas.clientHeight;let x=rnd(w-50,50),y=rnd(h-50,70),p=worldRef.current.player;if(Math.hypot(x-p.x,y-p.y)<120){x=(x+w/2)%w;y=(y+h/2)%h}arr.push({x,y,r,life,maxLife:life,age:0})};const pickupHit=(a:Point,b:Point)=>Math.abs(a.x-b.x)<=12&&Math.abs(a.y-b.y)<=12;const hazardHit=(a:Point,b:Point)=>{const l=Math.max(10,a.r*.35+b.r*.45);return Math.abs(a.x-b.x)<=l&&Math.abs(a.y-b.y)<=l};const fade=(q:Point)=>Math.min(1,(q.age||0)/.4,(q.life??1)/.8);
  const loop=(now:number)=>{const dt=Math.min((now-last)/1000,.034);last=now;const w=canvas.clientWidth,h=canvas.clientHeight,s=worldRef.current,cfg=LEVELS[s.level];ctx.clearRect(0,0,w,h);ctx.fillStyle="#090d14";ctx.fillRect(0,0,w,h);const grid=(now*.018*cfg.drift)%42;ctx.strokeStyle="rgba(100,233,202,.055)";ctx.lineWidth=1;for(let x=-42+grid;x<w+42;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-30*cfg.drift,h);ctx.stroke()}for(let y=-42+grid*.55;y<h+42;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y+12*cfg.drift);ctx.stroke()}
   if(modeRef.current==="playing"){s.time=Math.max(0,RUN_SECONDS-(now-s.started)/1000);const pressure=1+(RUN_SECONDS-s.time)/75;s.spawn-=dt;if(s.spawn<=0){spawn(s.signals,7,rnd(12,9));if(Math.random()<cfg.noiseChance)spawn(s.noise,rnd(16,10),rnd(8,5));if(Math.random()<.2)spawn(s.echoes,9,rnd(10,7));s.spawn=Math.max(.32,cfg.spawn/pressure)}const i=inputRef.current,p=s.player;let dx=i.x,dy=i.y;if(i.pointer){const d=Math.hypot(i.tx-p.x,i.ty-p.y);if(d>8){dx=(i.tx-p.x)/d;dy=(i.ty-p.y)/d}else i.pointer=false}const mag=Math.hypot(dx,dy)||1;p.vx=(p.vx||0)*.86+(dx/mag)*18;p.vy=(p.vy||0)*.86+(dy/mag)*18;p.x=Math.max(15,Math.min(w-15,p.x+(p.vx||0)*dt*4.8));p.y=Math.max(48,Math.min(h-15,p.y+(p.vy||0)*dt*4.8));for(const group of[s.signals,s.echoes,s.noise])for(const q of group){q.life=(q.life||0)-dt;q.age=(q.age||0)+dt}s.noise.forEach(n=>{const a=Math.atan2(p.y-n.y,p.x-n.x);n.x+=Math.cos(a)*dt*12*pressure*cfg.chase;n.y+=Math.sin(a)*dt*12*pressure*cfg.chase});let signalTaken=false;s.signals=s.signals.filter(q=>{if((q.life||0)<=0)return false;if(!signalTaken&&pickupHit(p,q)){signalTaken=true;s.score+=10*s.combo;s.combo=Math.min(8,s.combo+1);for(let k=0;k<8;k++)s.particles.push({x:q.x,y:q.y,r:2,vx:rnd(90,-90),vy:rnd(90,-90),life:1});return false}return true});let echoTaken=false;s.echoes=s.echoes.filter(q=>{if((q.life||0)<=0)return false;if(!echoTaken&&pickupHit(p,q)){echoTaken=true;s.health=Math.min(100,s.health+18);s.score+=25;return false}return true});s.noise=s.noise.filter(q=>{if((q.life||0)<=0)return false;if(hazardHit(p,q)){s.health-=cfg.damage;s.combo=1;s.flash=.18;return false}return q.x>-40&&q.x<w+40&&q.y>-40&&q.y<h+40});s.particles=s.particles.filter(q=>{q.life=(q.life||0)-dt;q.x+=(q.vx||0)*dt;q.y+=(q.vy||0)*dt;return(q.life||0)>0});s.flash=Math.max(0,s.flash-dt);if(s.health<=0||s.time<=0){modeRef.current="ended";setMode("ended")}uiTick-=dt;if(uiTick<=0){setScore(s.score);setHealth(Math.max(0,s.health));setTime(Math.ceil(s.time));setCombo(s.combo);uiTick=.1}}
   const glow=(q:Point,color:string)=>{ctx.shadowBlur=18;ctx.shadowColor=color;ctx.fillStyle=color;ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0};s.signals.forEach(q=>{ctx.globalAlpha=fade(q);glow(q,"#64e9ca")});s.echoes.forEach(q=>{ctx.globalAlpha=fade(q);ctx.strokeStyle="#f1c75b";ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,q.r+3+Math.sin(now/150)*2,0,Math.PI*2);ctx.stroke();glow(q,"#f1c75b")});s.noise.forEach(q=>{ctx.save();ctx.globalAlpha=fade(q);ctx.translate(q.x,q.y);ctx.rotate(now/700+q.x);ctx.fillStyle="#e55175";ctx.shadowBlur=14;ctx.shadowColor="#e55175";ctx.fillRect(-q.r,-q.r,q.r*2,q.r*2);ctx.restore()});s.particles.forEach(q=>{ctx.globalAlpha=q.life||0;glow(q,"#64e9ca")});ctx.globalAlpha=1;const p=s.player;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.atan2(p.vy||0,p.vx||0)+Math.PI/2);ctx.shadowBlur=22;ctx.shadowColor="#fff";ctx.fillStyle="#f4f7fb";ctx.beginPath();ctx.moveTo(0,-14);ctx.lineTo(10,10);ctx.lineTo(0,6);ctx.lineTo(-10,10);ctx.closePath();ctx.fill();ctx.restore();if(s.flash>0){ctx.fillStyle=`rgba(229,81,117,${s.flash*2})`;ctx.fillRect(0,0,w,h)}frameRef.current=requestAnimationFrame(loop)};frameRef.current=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(frameRef.current);removeEventListener("resize",resize)}},[]);

 useEffect(()=>{const timer=setInterval(()=>{if(modeRef.current!=="playing")return;const s=worldRef.current,elapsed=Math.max(0,RUN_SECONDS-s.time),acceleration=Math.min(2.4,1+elapsed/55);s.health-=LEVELS[s.level].decay*acceleration/10},100);return()=>clearInterval(timer)},[]);

 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();inputRef.current.tx=e.clientX-r.left;inputRef.current.ty=e.clientY-r.top;inputRef.current.pointer=true};const rank=score>1800?"CLEAR SIGNAL":score>900?"FIELD OPERATOR":score>350?"RELAY RUNNER":"LOST FREQUENCY";
 return <main className="shell"><header className="topbar"><div className="brand"><span className="brandmark"/>Signal Drift</div><div className="topnote">Archive 07 / unstable network</div></header><section className="gameframe"><div className="stage"><canvas ref={canvasRef} onPointerDown={point} aria-label="Signal Drift game field"/><div className="hud"><div className="stat"><span className="label">Time left</span><span className="value">{Math.floor(time/60)}:{String(time%60).padStart(2,"0")}</span></div><div className="stat"><span className="label">Signal</span><span className="value accent">{score.toString().padStart(5,"0")}</span></div><div className="stat"><span className="label">Chain</span><span className="value">×{combo}</span></div></div>{mode!=="playing"&&<div className="overlay"><div className="card">{mode==="intro"?<><div className="eyebrow">Survive for two minutes</div><h1>Carry the signal.</h1><p className="lede">Fly through green dots to score. Avoid pink blocks. Gold rings restore integrity.</p><div className="difficulty">{(Object.keys(LEVELS)as Level[]).map(key=><button key={key} className={`difficulty-option ${level===key?"selected":""}`} onClick={()=>chooseLevel(key)}><b>{LEVELS[key].label}</b><small>{LEVELS[key].note}</small></button>)}</div><button className="primary" onClick={begin}>Start transmission</button><div className="controls"><span className="key">WASD</span> or <span className="key">ARROWS</span> to steer · click/tap to move</div></>:<><div className="eyebrow">Transmission complete · {LEVELS[levelRef.current].label}</div><div className="end-score">{score}</div><span className="rank">{rank}</span><p className="lede">The field remembers every route. Try a harder transmission?</p><button className="primary" onClick={begin}>Run it again</button></>}</div></div>}</div><aside className="sidebar"><div className="panel"><h2>Your mission</h2><div className="rule"><span className="dot signal"/><span><b>Green dots = score</b><br/>Collect before they fade. Consecutive pickups multiply points.</span></div><div className="rule"><span className="dot echo"/><span><b>Gold rings = health</b><br/>Temporary fragments restore integrity.</span></div><div className="rule"><span className="dot noise"/><span><b>Pink blocks = danger</b><br/>They chase, damage and break your multiplier.</span></div></div><div className="panel"><h2>Integrity · {LEVELS[level].label}</h2><div className="meter"><span style={{width:`${health}%`}}/></div><div className="phase"><span>critical</span><span>{Math.round(health)}%</span><span>stable</span></div></div><div className="panel quote">“A clean signal is not the absence of noise. It is the route you choose through it.”</div></aside></section></main>;
}
